version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: web_app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../data:/data
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000
