# Generated by Django 5.2.8 on 2025-11-21 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=10)),
                ("county_code", models.CharField(max_length=10)),
                ("structure_number", models.CharField(max_length=50)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "features_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "facility_carried",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                (
                    "structure_kind",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "structure_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "deck_structure_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("main_unit_spans", models.IntegerField(blank=True, null=True)),
                ("max_span_len_mt", models.FloatField(blank=True, null=True)),
                ("structure_len_mt", models.FloatField(blank=True, null=True)),
                ("adt", models.IntegerField(blank=True, null=True)),
                ("year_adt", models.IntegerField(blank=True, null=True)),
                ("deck_cond", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "superstructure_cond",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "substructure_cond",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("operating_rating", models.FloatField(blank=True, null=True)),
                ("inventory_rating", models.FloatField(blank=True, null=True)),
                (
                    "structural_eval",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("data_year", models.IntegerField()),
            ],
            options={
                "ordering": ["-data_year"],
                "unique_together": {("structure_number", "data_year")},
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bridge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="bridges.bridge",
                    ),
                ),
            ],
        ),
    ]
